services:
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.swag
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./.env
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-UTC}'
      URL: '${DUCKDNS_URL}'
      SUBDOMAINS: '${DUCKDNS_SUBDOMAINS}'
      VALIDATION: 'duckdns'
      DUCKDNSTOKEN: '${DUCKDNS_TOKEN}'
      EMAIL: '${LETSENCRYPT_EMAIL}'
      ONLY_SUBDOMAINS: '${ONLY_SUBDOMAINS:-false}'
      STAGING: '${LE_STAGING:-false}'
    volumes:
      - ./frontend/swag-config:/config
    depends_on:
      - backend
